// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Dinhom_c
NumericVector Dinhom_c(NumericMatrix x, NumericMatrix bbox, NumericVector lambda, NumericVector bdist, double inf_int, NumericVector r);
RcppExport SEXP _sseg_Dinhom_c(SEXP xSEXP, SEXP bboxSEXP, SEXP lambdaSEXP, SEXP bdistSEXP, SEXP inf_intSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< double >::type inf_int(inf_intSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(Dinhom_c(x, bbox, lambda, bdist, inf_int, r));
    return rcpp_result_gen;
END_RCPP
}
// Dinhom_pair_c
NumericVector Dinhom_pair_c(int from, int to, NumericMatrix x, NumericMatrix bbox, NumericVector lambda, IntegerVector type, NumericVector bdist, NumericVector rho0, NumericVector r, int nmarks);
RcppExport SEXP _sseg_Dinhom_pair_c(SEXP fromSEXP, SEXP toSEXP, SEXP xSEXP, SEXP bboxSEXP, SEXP lambdaSEXP, SEXP typeSEXP, SEXP bdistSEXP, SEXP rho0SEXP, SEXP rSEXP, SEXP nmarksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nmarks(nmarksSEXP);
    rcpp_result_gen = Rcpp::wrap(Dinhom_pair_c(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks));
    return rcpp_result_gen;
END_RCPP
}
// Dinhom_pair_2_c
NumericVector Dinhom_pair_2_c(int from, int to, NumericMatrix x, NumericMatrix bbox, NumericVector lambda, IntegerVector type, NumericVector bdist, NumericVector rho0, NumericVector r, int nmarks);
RcppExport SEXP _sseg_Dinhom_pair_2_c(SEXP fromSEXP, SEXP toSEXP, SEXP xSEXP, SEXP bboxSEXP, SEXP lambdaSEXP, SEXP typeSEXP, SEXP bdistSEXP, SEXP rho0SEXP, SEXP rSEXP, SEXP nmarksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nmarks(nmarksSEXP);
    rcpp_result_gen = Rcpp::wrap(Dinhom_pair_2_c(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks));
    return rcpp_result_gen;
END_RCPP
}
// Dinhom_pair_graph_c
NumericVector Dinhom_pair_graph_c(int from, int to, NumericMatrix x, NumericMatrix bbox, NumericVector lambda, IntegerVector type, NumericVector bdist, NumericVector rho0, NumericVector r, int nmarks);
RcppExport SEXP _sseg_Dinhom_pair_graph_c(SEXP fromSEXP, SEXP toSEXP, SEXP xSEXP, SEXP bboxSEXP, SEXP lambdaSEXP, SEXP typeSEXP, SEXP bdistSEXP, SEXP rho0SEXP, SEXP rSEXP, SEXP nmarksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< int >::type to(toSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rho0(rho0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type nmarks(nmarksSEXP);
    rcpp_result_gen = Rcpp::wrap(Dinhom_pair_graph_c(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks));
    return rcpp_result_gen;
END_RCPP
}
// graph_c
List graph_c(NumericMatrix x, NumericMatrix bb, int gtype, NumericVector gpar, double MaxR);
RcppExport SEXP _sseg_graph_c(SEXP xSEXP, SEXP bbSEXP, SEXP gtypeSEXP, SEXP gparSEXP, SEXP MaxRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bb(bbSEXP);
    Rcpp::traits::input_parameter< int >::type gtype(gtypeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gpar(gparSEXP);
    Rcpp::traits::input_parameter< double >::type MaxR(MaxRSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_c(x, bb, gtype, gpar, MaxR));
    return rcpp_result_gen;
END_RCPP
}
// mingling_index_c_1st
NumericVector mingling_index_c_1st(NumericMatrix x, IntegerVector type, int ntypes, NumericMatrix bbox, NumericVector bdist, NumericVector r, IntegerVector targets, int ntype);
RcppExport SEXP _sseg_mingling_index_c_1st(SEXP xSEXP, SEXP typeSEXP, SEXP ntypesSEXP, SEXP bboxSEXP, SEXP bdistSEXP, SEXP rSEXP, SEXP targetsSEXP, SEXP ntypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< int >::type ntype(ntypeSEXP);
    rcpp_result_gen = Rcpp::wrap(mingling_index_c_1st(x, type, ntypes, bbox, bdist, r, targets, ntype));
    return rcpp_result_gen;
END_RCPP
}
// mingling_index_c_2nd
NumericVector mingling_index_c_2nd(NumericMatrix x, IntegerVector type, int ntypes, NumericMatrix bbox, NumericVector bdist, NumericVector r, IntegerVector targets, int ntype);
RcppExport SEXP _sseg_mingling_index_c_2nd(SEXP xSEXP, SEXP typeSEXP, SEXP ntypesSEXP, SEXP bboxSEXP, SEXP bdistSEXP, SEXP rSEXP, SEXP targetsSEXP, SEXP ntypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type ntypes(ntypesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bbox(bboxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bdist(bdistSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< int >::type ntype(ntypeSEXP);
    rcpp_result_gen = Rcpp::wrap(mingling_index_c_2nd(x, type, ntypes, bbox, bdist, r, targets, ntype));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _sseg_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sseg_Dinhom_c", (DL_FUNC) &_sseg_Dinhom_c, 6},
    {"_sseg_Dinhom_pair_c", (DL_FUNC) &_sseg_Dinhom_pair_c, 10},
    {"_sseg_Dinhom_pair_2_c", (DL_FUNC) &_sseg_Dinhom_pair_2_c, 10},
    {"_sseg_Dinhom_pair_graph_c", (DL_FUNC) &_sseg_Dinhom_pair_graph_c, 10},
    {"_sseg_graph_c", (DL_FUNC) &_sseg_graph_c, 5},
    {"_sseg_mingling_index_c_1st", (DL_FUNC) &_sseg_mingling_index_c_1st, 8},
    {"_sseg_mingling_index_c_2nd", (DL_FUNC) &_sseg_mingling_index_c_2nd, 8},
    {"_sseg_rcpp_hello", (DL_FUNC) &_sseg_rcpp_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_sseg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
