# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Dinhom_c <- function(x, bbox, lambda, bdist, inf_int, r) {
    .Call('_sseg_Dinhom_c', PACKAGE = 'sseg', x, bbox, lambda, bdist, inf_int, r)
}

Dinhom_pair_c <- function(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks) {
    .Call('_sseg_Dinhom_pair_c', PACKAGE = 'sseg', from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks)
}

Dinhom_pair_2_c <- function(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks) {
    .Call('_sseg_Dinhom_pair_2_c', PACKAGE = 'sseg', from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks)
}

Dinhom_pair_graph_c <- function(from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks) {
    .Call('_sseg_Dinhom_pair_graph_c', PACKAGE = 'sseg', from, to, x, bbox, lambda, type, bdist, rho0, r, nmarks)
}

graph_c <- function(x, bb, gtype = 1L, gpar = 0L, MaxR = 0) {
    .Call('_sseg_graph_c', PACKAGE = 'sseg', x, bb, gtype, gpar, MaxR)
}

mingling_index_c_1st <- function(x, type, ntypes, bbox, bdist, r, targets, ntype) {
    .Call('_sseg_mingling_index_c_1st', PACKAGE = 'sseg', x, type, ntypes, bbox, bdist, r, targets, ntype)
}

mingling_index_c_2nd <- function(x, type, ntypes, bbox, bdist, r, targets, ntype) {
    .Call('_sseg_mingling_index_c_2nd', PACKAGE = 'sseg', x, type, ntypes, bbox, bdist, r, targets, ntype)
}

rcpp_hello <- function() {
    .Call('_sseg_rcpp_hello', PACKAGE = 'sseg')
}

